# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-30 15:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftbucket',
            name='ammo_breakdown',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'given': {'avg': {}, 'totals': {}}, 'received': {'avg': {}, 'totals': {}}}),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='plane_lethality_no_assists',
            field=models.FloatField(default=0),
        ),
    ]
