# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 16:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftbucket',
            name='ammo_breakdown',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'given': {'avg': {}, 'totals': {}}, 'received': {'avg': {'all': 0.0, 'cannon': 0.0, 'mg': 0.0}, 'totals': {'all': {'count': 0, 'instances': 0}, 'cannon': {'count': 0, 'instances': 0}, 'mg': {'count': 0, 'instances': 0}}}}),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='plane_lethality_no_assists',
            field=models.FloatField(default=0),
        ),
    ]
